site_name: 'itchat'
pages:
- '介绍':
    - '项目简介': 'index.md'
extra_css: ['docs/bootstrap/css']
extra_javascript: ['docs/bootstrap/js']
theme_dir: 'docs/bootstrap'
repo_url: 'https://github.com/dissipator/walle-python'
